spring:
  application:
    name: musichub

  datasource:
    url: jdbc:postgresql://localhost:5432/musichub
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

jwt:
  secret: yourSuperSecretKey
  expiration: 86400000  # 1 day in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG